// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from "@/components/Navbar";
// import { Playfair_Display } from "next/font/google";
// import Footer from "@/components/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// const playfairDisplay = Playfair_Display({
//   weight: ["400", "700", "900"], // Common weights for Playfair
//   subsets: ["latin"],
//   variable: "--font-playfair",
// });

// export const metadata = {
//   title: "Dilli Darbar",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" className="bg-black">
//       <body 
//         className={`${geistSans.variable} ${geistMono.variable} ${playfairDisplay.variable} bg-black min-h-screen`}
//         suppressHydrationWarning={true}
//       >
//         <Navbar />
//         <div className="h-[80px] bg-black"></div>
//         {children}
//         <Footer/>
//       </body>
//     </html>
//   );
// }


import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Playfair_Display } from "next/font/google";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfairDisplay = Playfair_Display({
  weight: ["400", "700", "900"],
  subsets: ["latin"],
  variable: "--font-playfair",
});

// 🎯 SEO METADATA
export const metadata = {
  title: {
    template: '%s | Dilli Darbar Framingham',
    default: 'Dilli Darbar | Authentic North Indian Fine Dining Restaurant in Framingham, MA'
  },
  description: 'Experience the finest North Indian cuisine at Dilli Darbar, Framingham\'s premier fine dining Indian restaurant. Authentic flavors, elegant ambiance. Reservations: (508) 599-2222',
  keywords: [
    'Dilli Darbar',
    'North Indian restaurant Framingham',
    'Indian fine dining Massachusetts', 
    'authentic Indian food Framingham',
    'Indian restaurant near me',
    'Framingham restaurants'
  ],
  authors: [{ name: 'Dilli Darbar' }],
  metadataBase: new URL('https://yourwebsite.com'), // 🔄 Replace with your domain
  alternates: {
    canonical: '/',
  },
  openGraph: {
    title: 'Dilli Darbar | North Indian Fine Dining Framingham, MA',
    description: 'Authentic North Indian cuisine in Framingham, MA',
    url: 'https://yourwebsite.com', // 🔄 Replace with your domain
    siteName: 'Dilli Darbar',
    images: ['/logo-3.png'],
    locale: 'en_US',
    type: 'website',
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({ children }) {
  // 🏪 RESTAURANT SCHEMA
  const restaurantSchema = {
    '@context': 'https://schema.org',
    '@type': 'Restaurant',
    name: 'Dilli Darbar',
    description: 'Authentic North Indian fine dining restaurant in Framingham, MA',
    servesCuisine: 'North Indian',
    address: {
      '@type': 'PostalAddress',
      streetAddress: '[Your Street Address]', // 🔄 Add your address
      addressLocality: 'Framingham',
      addressRegion: 'MA',
      postalCode: '[Your ZIP]', // 🔄 Add your ZIP
      addressCountry: 'US'
    },
    telephone: '+1-508-599-2222',
    email: 'Dillidarbarma@gmail.com',
    url: 'https://yourwebsite.com', // 🔄 Replace with your domain
    priceRange: '$$$',
    acceptsReservations: true,
  };

  return (
    <html lang="en" className="bg-black">
      <head>
        {/* 📍 LOCAL SEO */}
        <meta name="geo.region" content="US-MA" />
        <meta name="geo.placename" content="Framingham" />
        <meta name="geo.position" content="42.3001;-71.4162" />
        
        {/* 🏪 RESTAURANT SCHEMA */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(restaurantSchema)
          }}
        />
      </head>
      <body 
        className={`${geistSans.variable} ${geistMono.variable} ${playfairDisplay.variable} bg-black min-h-screen`}
        suppressHydrationWarning={true}
      >
        <Navbar />
        <div className="h-[80px] bg-black"></div>
        {children}
        <Footer/>
      </body>
    </html>
  );
}